// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectPrisonBreak.Persistences;

namespace ProjectPrisonBreak.Migrations
{
    [DbContext(typeof(JusticaContext))]
    partial class JusticaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectPrisonBreak.Models.Bandido", b =>
                {
                    b.Property<int>("BandidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CadeiaId")
                        .HasColumnType("int");

                    b.Property<string>("Capivara")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cpf")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReuPrimario")
                        .HasColumnType("bit");

                    b.Property<string>("Vulgo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BandidoId");

                    b.HasIndex("CadeiaId");

                    b.ToTable("Bandidos");
                });

            modelBuilder.Entity("ProjectPrisonBreak.Models.Cadeia", b =>
                {
                    b.Property<int>("CadeiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CadeiaId");

                    b.ToTable("Cadeias");
                });

            modelBuilder.Entity("ProjectPrisonBreak.Models.Bandido", b =>
                {
                    b.HasOne("ProjectPrisonBreak.Models.Cadeia", "Cadeia")
                        .WithMany("Bandidos")
                        .HasForeignKey("CadeiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
